import { AuthMessages } from "@/components/authentication/auth-messages"

import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="flex h-screen flex-col items-center justify-center">
          {children}
        </main>
        <AuthMessages />
      </body>
    </html>
  )
}
